name: Run Python Script
on:
  workflow_dispatch: # Allows triggering via API or manual workflows
    inputs:
      scriptName:
        description: "Name of the script to execute (e.g., scrape_7zip.py)"
        required: true

jobs:
  execute-script:
    runs-on: ubuntu-latest # GitHub-hosted runner

    steps:
      # Step 1: Check out the repository to give access to script files
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python in the GitHub environment
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9" # Specify the Python version

      # Step 3: Install dependencies (if any)
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Execute the specified Python script
      - name: Execute Python Script
        run: |
          echo "Running ${{ inputs.scriptName }}"
          python scripts/${{ inputs.scriptName }}
