name: Run Python Script
on:
  workflow_dispatch: # Allows for manual or API-triggered execution
    inputs:
      scriptName:
        description: "Name of the Python script to execute"
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner environment
    steps:
      # Step 1: Checkout the repository where the scripts are stored
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment for running scripts
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9" # Version of Python to use

      # Step 3: Install Dependencies for Scripts
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          # If your script has libraries like `requests`, add them here
          pip install requests

      # Step 4: Run the Python script specified by scriptName
      - name: Run Python Script
        run: |
          echo "Running ${{ inputs.scriptName }}"
          python scripts/${{ inputs.scriptName }}
