name: Run Python Script
on:
  workflow_dispatch:
    inputs:
      scriptName:
        description: "Name of the script to execute"
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python Script
        id: run_script
        run: |
          echo "Running ${{ inputs.scriptName }}"
          output=$(python scripts/${{ inputs.scriptName }})
          echo $output

      - name: Send Output to Server Webhook
        if: always() # Ensure this step runs even if the script fails
        run: |
          curl -X POST "https://9rlvvbg3-3000.inc1.devtunnels.ms/api/webhook" \
               -H "Content-Type: application/json" \
               -d "{\"status\":\"success\", \"data\":\"$output\"}"
